apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
    name: http
    NodePort: 32000
  - port: 443
    targetPort: 443
    name: https
    NodePort: 32100
  type: NodePort