apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wd2Q=


# Valores executa no bash: echo -n "mongouser" | base64
# Valores executa no bash: echo -n "mongopwd" | base64